### PR TITLE
fix: fix error element has been destroyed

### PR DESCRIPTION
**Pull request by weishaodaren**
fix:  Cannot read properties of null (reading 'style')

### CODE REVIEW

**Comment by micku7zu** [comment]
Can you please provide more details when this can happen? 

What to do to replicate the error?

Thanks for pull request.

**Comment by weishaodaren** [comment]
> Can you please provide more details when this can happen?
> 
> What to do to replicate the error?
> 
> Thanks for pull request.

image
Click the `Destroy` button

**Comment by micku7zu** [comment]
Oh, yea. I missed that. Thanks!

Unfortunately, your fix will fix the JS error, but not the actual code logic error. 

I will fix it.

**Comment by micku7zu** [comment]
Thanks for pull request. I fixed it and released 1.8.1: https://github.com/micku7zu/vanilla-tilt.js/commit/967ab1accf4fdf5ce8a67eeac146e3035a7fe5be

**Pull request closed without merging**
