### PR TITLE
Device orientation support

### PR DESCRIPTION
**Pull request by matteo-rigon**
Hello, i wanted to take on the goal to support device orientation on mobile devices as requested in #21.

However, instead of redoing all tilt calculations based on device orientation i figured out it would have been easier to map the device orientation angle to a virtual mouse position on the tilting element, so that there is no need to edit other methods.

I added 5 new settings:
- **gyroscope**: Boolean to enable/disable device orientation detection,
- **gyroscopeMinAngleX**: This is the bottom limit of the device angle on X axis, meaning that a device rotated at this angle would tilt the element as if the mouse was on the left border of the element;
- **gyroscopeMaxAngleX**: This is the top limit of the device angle on X axis, meaning that a device rotated at this angle would tilt the element as if the mouse was on the right border of the element;
- **gyroscopeMinAngleY**: This is the bottom limit of the device angle on Y axis, meaning that a device rotated at this angle would tilt the element as if the mouse was on the top border of the element;
- **gyroscopeMaxAngleY**: This is the top limit of the device angle on Y axis, meaning that a device rotated at this angle would tilt the element as if the mouse was on the bottom border of the element;

I chose the following default values:
- gyroscopeMinAngleX: -30,
- gyroscopeMaxAngleX: 30,
- gyroscopeMinAngleY: 0,
 - gyroscopeMaxAngleY: 90,

These should set a decent starting point for most use cases since the "rest" position ( aka the position at which the tilt is 0) is 0 degrees on X axis and 45 degrees on Y axis, which is roughly how everybody keeps a phone in their hand.

If something in the code isn't clear, just ask 😄

### CODE REVIEW

**Comment by micku7zu** [comment]
Thanks a lot for the contribution! Unfortunately, I don't have access to a computer until December 10. When I'm back home this is the first item on my to do list!

**Comment by matteo-rigon** [comment]
No problem dude, no need to hurry 😄 
I reverted the changes on compiled dist and lib files so there is no bloat when checking the diff

**Comment by micku7zu** [comment]
I closed some issues today and made some commits. I hope I will have time to merge this too. Thank you again!

**Comment by matteo-rigon** [comment]
Hello @micku7zu , any updates on the merge? A christmas gift would be cool 😄

**Comment by micku7zu** [comment]
@matteo-rigon Thank you! I finally merged the pull request and updated the library to version 1.6.0. 
Updated the NPM package: https://www.npmjs.com/package/vanilla-tilt
Updated the releases page: https://github.com/micku7zu/vanilla-tilt.js/releases
Updated the documentation: https://github.com/micku7zu/vanilla-tilt.js
Updated the demo page: https://micku7zu.github.io/vanilla-tilt.js/

Also, added you to the contributors list and added the list in the README file and on the demo page.

Thanks a lot!

I think there are still a few things to be tuned for the gyroscope feature but I don't have enough time 😄

**Pull request merged**
